apiVersion: apps/v1
kind: Deployment
metadata:
  name: iothub-k8s-wilson-liao
  labels:
    name: assignment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: iothub
      student: wilson-liao
  template:
    metadata:
      labels:
        component: iothub
        student: wilson-liao
    spec:
      containers:
        - name: mqtt
          image: wilsonliao/iothub-demo:0.0.1
          resources:
            limits:
              cpu: 20m
              memory: 64Mi
              ephemeral-storage: 64Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: assignment-secret
                  key: ENSAAS_SERVICES
